name: Build Full VNRP

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build-windows-full:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Force Download All Submodules Manually
        shell: bash
        run: |
          rm -rf lib/omp-sdk
          git clone --recursive https://github.com/openmultiplayer/open.mp-sdk.git lib/omp-sdk
          rm -rf lib/omp-net
          git clone --recursive https://github.com/openmultiplayer/open.mp-network.git lib/omp-net

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Conan 1.x
        run: |
          python -m pip install --upgrade pip
          pip install "conan<2.0"

      - name: Setup DirectX SDK
        run: |
          git clone https://github.com/testing-laboratory/DirectX-SDK-June2010.git dxsdk
          $DxPath = Join-Path (Get-Location) "dxsdk"
          echo "DXSDK_DIR=$DxPath\" >> $env:GITHUB_ENV

      # --- BƯỚC KHÓA MÕM VS2022: Cấm compile file .fx (Shader) ---
      - name: Fix FXC Shader Compiler Error
        shell: bash
        run: |
          echo "" >> client/CMakeLists.txt
          echo "file(GLOB_RECURSE FX_FILES \"*.fx\" \"*.hlsl\")" >> client/CMakeLists.txt
          echo "set_source_files_properties(\${FX_FILES} PROPERTIES VS_TOOL_OVERRIDE \"None\" HEADER_FILE_ONLY TRUE)" >> client/CMakeLists.txt

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DDXSDK_DIR="$env:DXSDK_DIR" -DBUILD_CLIENT=ON .. -A Win32
          
      - name: Build Project
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sampvoice-full-release
          path: |
            build/**/*.dll
            build/**/*.asi
